version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  stayrai:
    image: stayrai/reef-pi-monolith:latest
    container_name: stayrai
    privileged: true
    ports:
      - "8085:8085"
    volumes:
      - ./data:/home/ubuntu/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      #vcgencmd dependencies
      - /lib/aarch64-linux-gnu/libvchiq_arm.so.0:/lib/aarch64-linux-gnu/libvchiq_arm.so.0
      - /lib/aarch64-linux-gnu/libvcos.so.0:/lib/aarch64-linux-gnu/libvcos.so.0
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    depends_on:
      - mosquitto
      - watchtower
      - txwifi
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"
  txwifi:
    image: stayrai/txwifi:latest
    container_name: txwifi
    privileged: true
    volumes:
      - ./wificfg.json:/cfg/wificfg.json
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "host"
    restart: always
    depends_on:
      - watchtower
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # Default Websocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    depends_on:
      - watchtower
      - txwifi
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"